const currencies = [
    { code: "USD", name: "United States Dollar", flag: "https://flagcdn.com/us.svg" },
    { code: "EUR", name: "Euro", flag: "https://flagcdn.com/eu.svg" },
    { code: "JPY", name: "Japanese Yen", flag: "https://flagcdn.com/jp.svg" },
    { code: "GBP", name: "British Pound Sterling", flag: "https://flagcdn.com/gb.svg" },
    { code: "AUD", name: "Australian Dollar", flag: "https://flagcdn.com/au.svg" },
    { code: "CAD", name: "Canadian Dollar", flag: "https://flagcdn.com/ca.svg" },
    { code: "CHF", name: "Swiss Franc", flag: "https://flagcdn.com/ch.svg" },
    { code: "CNY", name: "Chinese Yuan", flag: "https://flagcdn.com/cn.svg" },
    { code: "SEK", name: "Swedish Krona", flag: "https://flagcdn.com/se.svg" },
    { code: "NZD", name: "New Zealand Dollar", flag: "https://flagcdn.com/nz.svg" },
    { code: "MXN", name: "Mexican Peso", flag: "https://flagcdn.com/mx.svg" },
    { code: "SGD", name: "Singapore Dollar", flag: "https://flagcdn.com/sg.svg" },
    { code: "HKD", name: "Hong Kong Dollar", flag: "https://flagcdn.com/hk.svg" },
    { code: "NOK", name: "Norwegian Krone", flag: "https://flagcdn.com/no.svg" },
    { code: "KRW", name: "South Korean Won", flag: "https://flagcdn.com/kr.svg" },
    { code: "TRY", name: "Turkish Lira", flag: "https://flagcdn.com/tr.svg" },
    { code: "INR", name: "Indian Rupee", flag: "https://flagcdn.com/in.svg" },
    { code: "RUB", name: "Russian Ruble", flag: "https://flagcdn.com/ru.svg" },
    { code: "ZAR", name: "South African Rand", flag: "https://flagcdn.com/za.svg" },
    { code: "BRL", name: "Brazilian Real", flag: "https://flagcdn.com/br.svg" },
    { code: "MYR", name: "Malaysian Ringgit", flag: "https://flagcdn.com/my.svg" },
    { code: "THB", name: "Thai Baht", flag: "https://flagcdn.com/th.svg" },
    { code: "IDR", name: "Indonesian Rupiah", flag: "https://flagcdn.com/id.svg" },
    { code: "PLN", name: "Polish Zloty", flag: "https://flagcdn.com/pl.svg" },
    { code: "DKK", name: "Danish Krone", flag: "https://flagcdn.com/dk.svg" },
    { code: "CZK", name: "Czech Koruna", flag: "https://flagcdn.com/cz.svg" },
    { code: "HUF", name: "Hungarian Forint", flag: "https://flagcdn.com/hu.svg" },
    { code: "ILS", name: "Israeli New Shekel", flag: "https://flagcdn.com/il.svg" },
    { code: "PHP", name: "Philippine Peso", flag: "https://flagcdn.com/ph.svg" },
    { code: "AED", name: "United Arab Emirates Dirham", flag: "https://flagcdn.com/ae.svg" },
    { code: "SAR", name: "Saudi Riyal", flag: "https://flagcdn.com/sa.svg" },
    { code: "ARS", name: "Argentine Peso", flag: "https://flagcdn.com/ar.svg" },
    { code: "CLP", name: "Chilean Peso", flag: "https://flagcdn.com/cl.svg" },
    { code: "PKR", name: "Pakistani Rupee", flag: "https://flagcdn.com/pk.svg" },
    { code: "EGP", name: "Egyptian Pound", flag: "https://flagcdn.com/eg.svg" },
    { code: "BDT", name: "Bangladeshi Taka", flag: "https://flagcdn.com/bd.svg" },
    { code: "NGN", name: "Nigerian Naira", flag: "https://flagcdn.com/ng.svg" },
    { code: "KES", name: "Kenyan Shilling", flag: "https://flagcdn.com/ke.svg" },
    { code: "GHS", name: "Ghanaian Cedi", flag: "https://flagcdn.com/gh.svg" },
    { code: "UGX", name: "Ugandan Shilling", flag: "https://flagcdn.com/ug.svg" },
    { code: "VND", name: "Vietnamese Dong", flag: "https://flagcdn.com/vn.svg" },
    { code: "XOF", name: "West African CFA Franc", flag: "https://flagcdn.com/sn.svg" },
    { code: "XAF", name: "Central African CFA Franc", flag: "https://flagcdn.com/cm.svg" },
    { code: "MAD", name: "Moroccan Dirham", flag: "https://flagcdn.com/ma.svg" },
    { code: "TND", name: "Tunisian Dinar", flag: "https://flagcdn.com/tn.svg" },
    { code: "BHD", name: "Bahraini Dinar", flag: "https://flagcdn.com/bh.svg" },
    { code: "OMR", name: "Omani Rial", flag: "https://flagcdn.com/om.svg" }
  ];
  